// lib/presets/ai/nodes.ts
// AI 算法工程师知识树：节点定义（拓扑顺序 = 学习计划顺序）
// 从 lib/presets/ai.ts 拆分而来，内容保持不变

import type { KnowledgeNode } from "../../types";

export const AI_NODES: KnowledgeNode[] = [
  // ===== 机器学习基础（8 个节点） =====
  {
    id: "ai-ml-fundamentals",
    title: "机器学习基础",
    difficulty: 2,
    prerequisites: [],
    frequency: "高",
    bigTech: true,
    summary: "监督/无监督/强化学习、偏差-方差权衡、过拟合与欠拟合、交叉验证、训练/验证/测试集划分、生成模型与判别模型。",
    mastery: 0,
  },
  {
    id: "ai-linear-models",
    title: "线性模型（回归与分类）",
    difficulty: 3,
    prerequisites: ["ai-ml-fundamentals"],
    frequency: "高",
    bigTech: true,
    summary: "线性回归最小二乘与梯度下降、逻辑回归与交叉熵、L1/L2 正则化与稀疏解、Softmax 多分类、大规模 CTR 应用。",
    mastery: 0,
  },
  {
    id: "ai-tree-models",
    title: "树模型与 GBDT 系列",
    difficulty: 3,
    prerequisites: ["ai-ml-fundamentals"],
    frequency: "高",
    bigTech: true,
    summary: "决策树划分标准、随机森林 Bagging、GBDT/XGBoost/LightGBM/CatBoost 原理与改进、特征重要性、工业实战。",
    mastery: 0,
  },
  {
    id: "ai-svm",
    title: "SVM 与核方法",
    difficulty: 4,
    prerequisites: ["ai-ml-fundamentals"],
    frequency: "中",
    summary: "最大间隔、软间隔与松弛变量、核函数（线性/RBF/多项式）、对偶问题与 SMO、多分类、SVR、SVM vs 逻辑回归。",
    mastery: 0,
  },
  {
    id: "ai-ensemble",
    title: "集成学习",
    difficulty: 3,
    prerequisites: ["ai-tree-models"],
    frequency: "高",
    bigTech: true,
    summary: "Bagging vs Boosting、Stacking/Blending、多样性来源、XGBoost vs 随机森林选型、多模型融合工业实践。",
    mastery: 0,
  },
  {
    id: "ai-optimization",
    title: "优化算法",
    difficulty: 4,
    prerequisites: ["ai-ml-fundamentals"],
    frequency: "高",
    bigTech: true,
    summary: "梯度下降变体、Momentum/RMSProp/Adam 演进、AdamW 解耦权重衰减、学习率调度 warmup+cosine、二阶方法、梯度裁剪。",
    mastery: 0,
  },
  {
    id: "ai-evaluation",
    title: "评估指标与 A/B 测试",
    difficulty: 3,
    prerequisites: ["ai-ml-fundamentals"],
    frequency: "高",
    bigTech: true,
    summary: "分类（P/R/F1/AUC）、ROC vs PR、回归（MAE/MSE/MAPE）、排序（NDCG/MRR/MAP）、A/B 测试与显著性、在线离线指标对齐。",
    mastery: 0,
  },
  {
    id: "ai-feature-eng",
    title: "特征工程",
    difficulty: 3,
    prerequisites: ["ai-ml-fundamentals"],
    frequency: "高",
    bigTech: true,
    summary: "数值/类别特征处理、特征选择、特征交叉、自动特征与哈希、时间序列特征、推荐系统特征工程实战。",
    mastery: 0,
  },
  // ===== 深度学习（6 个节点） =====
  {
    id: "ai-nn-fundamentals",
    title: "神经网络基础",
    difficulty: 4,
    prerequisites: ["ai-ml-fundamentals", "ai-optimization"],
    frequency: "高",
    bigTech: true,
    summary: "反向传播链式法则、激活函数（ReLU/Sigmoid/GELU）、权重初始化（Xavier/He）、BatchNorm/Dropout、梯度消失爆炸、LayerNorm。",
    mastery: 0,
  },
  {
    id: "ai-cnn",
    title: "CNN 卷积神经网络",
    difficulty: 4,
    prerequisites: ["ai-nn-fundamentals"],
    frequency: "高",
    bigTech: true,
    summary: "卷积/池化/感受野、ResNet 残差连接、1×1 卷积、经典架构演进、深度可分离卷积轻量化、迁移学习微调、backbone 选型。",
    mastery: 0,
  },
  {
    id: "ai-rnn",
    title: "RNN/LSTM/GRU",
    difficulty: 4,
    prerequisites: ["ai-nn-fundamentals"],
    frequency: "高",
    summary: "RNN 梯度消失、LSTM 门控机制、GRU 简化、双向 RNN、Seq2Seq 与注意力、梯度裁剪、语音/OCR 应用。",
    mastery: 0,
  },
  {
    id: "ai-transformer",
    title: "Transformer",
    difficulty: 5,
    prerequisites: ["ai-rnn"],
    frequency: "高",
    bigTech: true,
    summary: "Self-Attention、多头注意力、位置编码/RoPE、LayerNorm Pre/Post-Norm、Encoder-Decoder 与因果掩码、训练技巧、长序列优化。",
    mastery: 0,
  },
  {
    id: "ai-pretrain",
    title: "预训练模型",
    difficulty: 5,
    prerequisites: ["ai-transformer"],
    frequency: "高",
    bigTech: true,
    summary: "BERT MLM vs GPT 自回归、T5、对比学习 SimCLR/CLIP、Prompt/Prefix Tuning、LoRA/QLoRA、scaling law、预训练工程。",
    mastery: 0,
  },
  {
    id: "ai-frameworks",
    title: "深度学习框架",
    difficulty: 3,
    prerequisites: ["ai-nn-fundamentals"],
    frequency: "中",
    bigTech: true,
    summary: "PyTorch autograd 动态图、nn.Module、混合精度训练、DDP 分布式训练、模型保存加载、TF/PyTorch 对比、Megatron/DeepSpeed。",
    mastery: 0,
  },
  // ===== CV 方向（4 个节点） =====
  {
    id: "ai-cv-classification",
    title: "图像分类",
    difficulty: 3,
    prerequisites: ["ai-cnn"],
    frequency: "中",
    bigTech: true,
    summary: "数据增强、迁移学习、ResNet 变体、Vision Transformer、知识蒸馏、长尾分布分类、商品识别工业落地。",
    mastery: 0,
  },
  {
    id: "ai-cv-detection",
    title: "目标检测",
    difficulty: 4,
    prerequisites: ["ai-cnn"],
    frequency: "高",
    bigTech: true,
    summary: "YOLO 单阶段、Faster R-CNN 两阶段、DETR、NMS/Soft-NMS、Anchor-free、mAP 评估、无人配送/安防应用。",
    mastery: 0,
  },
  {
    id: "ai-cv-segmentation",
    title: "图像分割",
    difficulty: 4,
    prerequisites: ["ai-cnn"],
    frequency: "中",
    bigTech: true,
    summary: "语义/实例/全景分割、U-Net、DeepLab 空洞卷积、Mask R-CNN、分割损失、医学图像、自动驾驶分割。",
    mastery: 0,
  },
  {
    id: "ai-cv-generative",
    title: "生成模型",
    difficulty: 5,
    prerequisites: ["ai-cnn"],
    frequency: "高",
    bigTech: true,
    summary: "GAN 原理与训练、VAE、Diffusion 模型、Stable Diffusion、FID/IS 评估、AIGC 图像生成应用。",
    mastery: 0,
  },
  // ===== NLP 方向（4 个节点） =====
  {
    id: "ai-nlp-fundamentals",
    title: "NLP 基础",
    difficulty: 3,
    prerequisites: ["ai-ml-fundamentals"],
    frequency: "中",
    summary: "分词（BPE/WordPiece）、Word2Vec（CBOW/Skip-gram）、GloVe、FastText、词向量评估、子词、中文分词与预训练。",
    mastery: 0,
  },
  {
    id: "ai-nlp-embeddings",
    title: "上下文向量与句向量",
    difficulty: 4,
    prerequisites: ["ai-nlp-fundamentals", "ai-transformer"],
    frequency: "高",
    bigTech: true,
    summary: "ELMo、BERT 嵌入、句向量 SBERT、SimCSE 对比学习、Embedding 检索、向量数据库、语义检索工业应用。",
    mastery: 0,
  },
  {
    id: "ai-nlp-sequence",
    title: "序列任务",
    difficulty: 4,
    prerequisites: ["ai-nlp-embeddings"],
    frequency: "中",
    bigTech: true,
    summary: "NER、POS 标注、文本分类、CRF、序列标注评估、BERT 微调序列任务、医疗/法律 NER 工业应用。",
    mastery: 0,
  },
  {
    id: "ai-nlp-generation",
    title: "生成任务",
    difficulty: 5,
    prerequisites: ["ai-pretrain"],
    frequency: "高",
    bigTech: true,
    summary: "摘要生成、机器翻译、对话系统、代码生成、解码策略（beam search/sampling）、BLEU/ROUGE 评估、LLM 生成应用。",
    mastery: 0,
  },
  // ===== 推荐系统（3 个节点） =====
  {
    id: "ai-rec-fundamentals",
    title: "推荐基础",
    difficulty: 3,
    prerequisites: ["ai-ml-fundamentals"],
    frequency: "高",
    bigTech: true,
    summary: "协同过滤（UserCF/ItemCF）、矩阵分解、召回排序双塔、冷启动、多路召回、FM、抖音召回策略实战。",
    mastery: 0,
  },
  {
    id: "ai-rec-deep",
    title: "深度推荐模型",
    difficulty: 4,
    prerequisites: ["ai-rec-fundamentals", "ai-nn-fundamentals"],
    frequency: "高",
    bigTech: true,
    summary: "Wide&Deep、DeepFM、DIN/DIEN 注意力序列兴趣、多目标优化（MMoE/PLE）、多任务损失加权、淘宝搜索排序演进。",
    mastery: 0,
  },
  {
    id: "ai-rec-engineering",
    title: "推荐工程化",
    difficulty: 4,
    prerequisites: ["ai-rec-deep"],
    frequency: "高",
    bigTech: true,
    summary: "召回-粗排-精排-重排漏斗、重排多样性（MMR/DPP）、实时特征、在线学习、E&E 探索利用、推荐系统工程架构。",
    mastery: 0,
  },
  // ===== 强化学习（2 个节点） =====
  {
    id: "ai-rl-fundamentals",
    title: "强化学习基础",
    difficulty: 4,
    prerequisites: ["ai-ml-fundamentals"],
    frequency: "中",
    bigTech: true,
    summary: "MDP、Q-Learning、SARSA、Policy Gradient、Actor-Critic、DQN、RL 在推荐/广告的应用。",
    mastery: 0,
  },
  {
    id: "ai-rl-advanced",
    title: "强化学习进阶",
    difficulty: 5,
    prerequisites: ["ai-rl-fundamentals", "ai-pretrain"],
    frequency: "高",
    bigTech: true,
    summary: "PPO、RLHF 三阶段、奖励建模、DPO、GRPO、RLHF 工程挑战、对齐实战。",
    mastery: 0,
  },
  // ===== 前沿与部署（3 个节点） =====
  {
    id: "ai-multimodal",
    title: "多模态",
    difficulty: 5,
    prerequisites: ["ai-pretrain", "ai-cnn"],
    frequency: "高",
    bigTech: true,
    summary: "CLIP、BLIP、Visual Language Model、图文检索、多模态对齐、VQA、多模态大模型应用。",
    mastery: 0,
  },
  {
    id: "ai-model-deploy",
    title: "模型部署",
    difficulty: 4,
    prerequisites: ["ai-frameworks"],
    frequency: "高",
    bigTech: true,
    summary: "模型量化、知识蒸馏、ONNX、TensorRT、模型服务化、推理优化 KV Cache、大模型部署。",
    mastery: 0,
  },
  {
    id: "ai-mlops",
    title: "MLOps",
    difficulty: 3,
    prerequisites: ["ai-model-deploy"],
    frequency: "中",
    bigTech: true,
    summary: "实验管理、模型注册、数据版本、模型监控漂移、CI/CD for ML、特征平台、MLOps 平台建设。",
    mastery: 0,
  },
];
